###################################
#服务启动端口的配置
###################################
server:
  port: 8000

###############################################################
# eureka 的相关配置
# 如果不需要 结合eureka 使用，可以不要这一段配置
###############################################################
eureka:
  client:
    service-url:
      defaultZone: http://123.56.60.46:1001/eureka/,http://123.56.60.46:1002/eureka/,http://123.56.60.46:1003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: gateway-1
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

spring:
  application:
    name: gateway-service
  cloud:
    #################################
    #   gateway相关配置
    #################################
    gateway:
      discovery:
        locator:
          enabled: true
      #    路由定义
      routes:
        - id: auth-service
          uri: lb://auth-service:5001
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://user-service:6001
          predicates:
            - Path=/user/**