package com.yu.dao;

import com.yu.entity.BookStock;
import java.util.List;

public interface BookStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbggenerated Wed Jun 03 21:17:59 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbggenerated Wed Jun 03 21:17:59 CST 2020
     */
    int insert(BookStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbggenerated Wed Jun 03 21:17:59 CST 2020
     */
    BookStock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbggenerated Wed Jun 03 21:17:59 CST 2020
     */
    List<BookStock> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbggenerated Wed Jun 03 21:17:59 CST 2020
     */
    int updateByPrimaryKey(BookStock record);
}