package com.yu.dao;

import com.yu.entity.BookClassify;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BookClassifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_classify
     *
     * @mbggenerated Wed Jun 03 09:38:20 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_classify
     *
     * @mbggenerated Wed Jun 03 09:38:20 CST 2020
     */
    int insert(BookClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_classify
     *
     * @mbggenerated Wed Jun 03 09:38:20 CST 2020
     */
    BookClassify selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_classify
     *
     * @mbggenerated Wed Jun 03 09:38:20 CST 2020
     */
    List<BookClassify> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_classify
     *
     * @mbggenerated Wed Jun 03 09:38:20 CST 2020
     */
    int updateByPrimaryKey(BookClassify record);

    /**
     * 根据分类编码查询
     * @param bookClassifyCode
     * @return
     */
    BookClassify selectByBookClassifyCode(@Param("bookClassifyCode") String bookClassifyCode);

    /**
     * 根据分类名称查询
     * @param bookClassifyName
     * @return
     */
    BookClassify selectByBookClassifyName(@Param("bookClassifyName") String bookClassifyName);
}